name: "Track Update Suggestion"
description: "Track update suggestion form for team members and contributors only!"
labels: ["track", "update", "discussion"]
body:
- type: "markdown"
  attributes:
    value: "This form **only** serves Retro Rewind **team members and contributors** to suggest track updates to the dev team.\n\nPeople outside of the team are not permitted to raise track update suggestions. Feel free to discuss your ideas on the [Retro Rewind Discord Server](https://discord.gg/RetroRewind). The philosophy behind the team not taking direct track update suggestions can be found in the feature-suggestions channel on Discord."
- type: "markdown"
  attributes:
    value: "### Suggestion guidelines\n- Please only suggest track updates, that you expect a significant number of the broad Retro Rewind player base to enjoy.\n  - Examples for this are: Improved item box placement, KCL changes etc."
- type: "checkboxes"
  attributes:
    label: "Authorization check"
    description: "By checking this box, you agree that you are authorized to make a track update suggestion. If you are not authorized, your issue may be closed without explanation."
    options:
    - label: "Yes"
      required: true
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Version"
    description: "What version is the pack on, at the time of making this suggestion?"
    placeholder: "v6.7"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Track update description"
    description: "What would the track update you're suggesting do?"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Pitch"
    description: "What makes this track update stand out and be useful for the broad Retro Rewind player base?"
  validations:
    required: true
